version: '2'

services:

  ####################### bsides-cpt-ctf

  1506-agent407:
    build: ./bsides-cpt-ctf-2019/agent407/.
    restart: on-failure
    ports:
      - "10000-10010:80"
    network_mode: bridge

  1506-darkbins:
    build: ./bsides-cpt-ctf-2019/darkbins/.
    restart: on-failure
    ports:
      - "10010-10020:80"
    network_mode: bridge

  1506-diffie:
    build: ./bsides-cpt-ctf-2019/diffie/.
    restart: on-failure
    ports:
      - "10020-10030:80"
    network_mode: bridge
  
  1506-ebook:
    build: ./bsides-cpt-ctf-2019/ebook/.
    restart: on-failure
    ports:
      - "10030-10040:80"
    network_mode: bridge

  1506-enigma:
    build: ./bsides-cpt-ctf-2019/enigma/.
    restart: on-failure
    ports:
      - "10040-10050:80"
    network_mode: bridge
  
  1506-gillette:
    build: ./bsides-cpt-ctf-2019/gillette/.
    restart: on-failure
    ports:
      - "10050-10060:80"
    network_mode: bridge

  1506-giveme:
    build: ./bsides-cpt-ctf-2019/giveme/.
    restart: on-failure
    ports:
      - "10060-10070:80"
    network_mode: bridge

  1506-origin:
    build: ./bsides-cpt-ctf-2019/origin/.
    restart: on-failure
    ports:
      - "10070-10080:80"
    network_mode: bridge

  ######################## Challenges-by-l4wio

  1506-prisonbreak:
      build: ./Challenges-by-l4wio/0x3004/150-prisonbreakseason2/.
      restart: on-failure
      ports:
          - "10080-10090:3500"
# works
  1506-xyzbank:
      build: ./Challenges-by-l4wio/0x3004/200-XYZBANK/.
      restart: on-failure
      ports:
          - "10090-10100:3580"
      networks:
          - 200-xyzbank
      depends_on:
          - 200-xyzbank-mysql
      links:
          - "200-xyzbank-mysql:database"
# works but no solutions
  1506-xyztemplate:
      build: ./Challenges-by-l4wio/0x3004/250-XYZTemplate/.
      restart: on-failure
      ports:
          - "10100-10110:4000"
# works but didnt get it
  1506-cryptowww:
      build:  ./Challenges-by-l4wio/0x3004/cryptowww/.
      restart: on-failure
      ports:
          - "10110-10120:80"
# works looks like I can solve it, have to spend time on it
  1506-curlstory:
      build:  ./Challenges-by-l4wio/challs.manhluat.org/curl_story_part_1/.
      restart: on-failure
      ports:
          - "10120-10130:80"

  1506-luckygame:
      build:  ./Challenges-by-l4wio/0ctf_final-2017/luckygame/.
      restart: on-failure
      environment:
          MYSQL_USER: strange_slime
          MYSQL_PASSWORD: temp3st_infinite
          MYSQL_ROOT_PASSWORD: temp3st_infinite
          MYSQL_DATABASE: luckygame
      volumes: 
          - ./Challenges-by-l4wio/0ctf_final-2017/luckygame/.:/var/www/html
      ports:
          - "10130-10140:80"
      depends_on:
          - luckygame-mysql
      links:
          - luckygame-mysql:luckygame-mysql
      networks:
          - luckygame
#works but index.html to improve and idk whats the point            
  1506-loginme:
      build: ./Challenges-by-l4wio/0ctf_quals-2018/LoginMe/.
      restart: on-failure
      ports:
      - "10140-10150:8081"
      depends_on:
      - "loginme-mongo"
      links:
      - loginme-mongo:loginme-mongo
      volumes:
      - ./Challenges-by-l4wio/0ctf_quals-2018/LoginMe/.:/usr/src/app
      - /usr/src/app/node_modules
      networks:
      - loginme

  ########################CJ2018

  1506-warmup:
    build: ./CJ2018/p00-warmup/.
    restart: on-failure
    ports:
      - "10150-10160:80"
    network_mode: bridge

  1506-firmware:
    build: ./CJ2018/p01-firmware/.
    restart: on-failure
    ports:
      - "10160-10170:8000"
    network_mode: bridge

  1506-sandbox:
    build: ./CJ2018/p02-sandbox/.
    restart: on-failure
    ports:
      - "10170-10180:80"
    network_mode: bridge
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  
  1506-imagemanipulator:
    build: ./CJ2018/p03-imagemanipulator/.
    restart: on-failure
    ports:
      - "10180-10190:80"
    network_mode: bridge

  1506-coderunner:
    build: ./CJ2018/p04-coderunner/.
    restart: on-failure
    ports:
      - "10190-10200:80"
    network_mode: bridge

  1506-exifreader: 
    build: ./CJ2018/p07-exifreader/.
    restart: on-failure
    ports:
      - "10200-10210:8000"
    network_mode: bridge
  
##################### Random-Challenge-Dockerfiles

  1506-homework:
    build: ./Random-Challenge-Dockerfiles/web/2018-suctf-homework/.
    restart: on-failure
    depends_on:
      - 2018-suctf-homework-mysql
    links:
      - 2018-suctf-homework-mysql:homework-mysql
    ports:
      - '10210-10220:80'
    volumes:
      - ./Random-Challenge-Dockerfiles/web/2018-suctf-homework/source/:/var/www/html
      - ./Random-Challenge-Dockerfiles/web/2018-suctf-homework/logs:/var/log/apache2
    stdin_open: true

  1506-ogeek:
    build: ./Random-Challenge-Dockerfiles/web/2019-ogeek-AndroidPHP/.
    restart: on-failure
    ports:
      - "10220-10230:80"

  # databases
  200-xyzbank-mysql:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_USER: strange_dragon
        MYSQL_PASSWORD: how_d0_you_turn_THIS_on
        MYSQL_ROOT_PASSWORD: how_d0_you_turn_THIS_on
        MYSQL_DATABASE: unit_cyber_db
      ports:
          - "3300-3310:3306"
      networks:
          - 200-xyzbank
      volumes:
          - "./Challenges-by-l4wio/0x3004/200-XYZBANK/dump.sql:/docker-entrypoint-initdb.d/1.sql"
          - 200-xyzbank-db:/var/lib/mysql

  luckygame-mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
      restart: always
      environment:
        MYSQL_USER: strange_slime
        MYSQL_PASSWORD: temp3st_infinite
        MYSQL_ROOT_PASSWORD: temp3st_infinite
        MYSQL_DATABASE: luckygame
      ports:
          - "3710-3720:3306"
      networks:
          - luckygame
      volumes:
          - luckygame-db:/var/lib/mysql
          - ./Challenges-by-l4wio/0ctf_final-2017/luckygame/dump.sql:/docker-entrypoint-initdb.d/1.sql"

  2018-suctf-homework-mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - ./Random-Challenge-Dockerfiles/web/2018-suctf-homework/database.sql:/docker-entrypoint-initdb.d/database.sql
      - 2018-suctf-homework-volume:/var/lib/mysql
      - ./Random-Challenge-Dockerfiles/web/2018-suctf-homework/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      - MYSQL_DATABASE=ctf
      - MYSQL_ROOT_PASSWORD=root
    ports:
        - "3720-3730:3306"

  loginme-mongo:
      image: "mongo"
      ports:
      - "27017:27017"
      networks:
      - loginme

volumes:
  200-xyzbank-db:
  luckygame-db:
  2018-suctf-homework-volume:

networks:
  200-xyzbank:
  luckygame:
  loginme: