version: '2'

services:
  web:
    image: php:5.6.40-apache
    ports:
      - '9999:80'
    volumes:
      - ./src:/var/www/html
      - ./log:/var/log/apache2
      - ./flag:/flag
    stdin_open: true
