version: '2'

services:

  agent407:
    build: ./agent407/.
    restart: on-failure
    ports:
      - "10000-10010:80"
    network_mode: bridge

  darkbins:
    build: ./darkbins/.
    restart: on-failure
    ports:
      - "10010-10020:80"
    network_mode: bridge

  diffie:
    build: ./diffie/.
    restart: on-failure
    ports:
      - "10020-10030:80"
    network_mode: bridge
  
  ebook:
    build: ./ebook/.
    restart: on-failure
    ports:
      - "10030-10040:80"
    network_mode: bridge

  enigma:
    build: ./enigma/.
    restart: on-failure
    ports:
      - "10040-10050:80"
    network_mode: bridge
  
  gillette:
    build: ./gillette/.
    restart: on-failure
    ports:
      - "10050-10060:80"
    network_mode: bridge

  giveme:
    build: ./giveme/.
    restart: on-failure
    ports:
      - "10060-10070:80"
    network_mode: bridge

  origin:
    build: ./origin/.
    restart: on-failure
    ports:
      - "10070-10080:80"
    network_mode: bridge