version: '2'

services:
        web:
                build: .
                ports:
                        - '10016:80'
                stdin_open: true
                tty: true
                volumes:
                        - ./logs:/var/log/apache2
                        - ./flag:/flag
