version: '3.1'
services:

  loginme:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - "loginme-mongo"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - loginme

  loginme-mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
      - loginme

networks:
  loginme:
